---
title: "Untitled"
output: html_document
---

```{r}

# check your package library path 
.libPaths()

# grab old packages names
old_packages <- installed.packages(lib.loc = "/home/jasmine/R/x86_64-pc-linux-gnu-library/3.6")
old_packages <- as.data.frame(old_packages)
list.of.packages <- unlist(old_packages$Package)

# remove old packages 
remove.packages( installed.packages( priority = "NA" )[,1] )

# reinstall all packages 
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.of.packages,function(x){library(x,character.only=TRUE)})

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Association Analysis

```{r}

install.packages("installr")

library(installr)
update.packages(ask = FALSE, checkBuilt = TRUE)

```



```{r}
# Installing the requiredlibrary 
#
install.packages("devtools")

library("devtools")
install_github("mhahsler/arules")

install.packages("arules")

devtools::install_github("mhahsler/arules")

# Loading the library
#
library(arules)

```




```{r}
# load the dataset using fread() funcion and instantiate it
path <- "http://bit.ly/SupermarketDatasetII"
super <- read.transactions(path, sep = ",")
```


