---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Anomaly Detection

```{r}
# Installing the required library 
#
devtools::install_github("business-science/anomalize")

install.packages("tidyverse")
library(tidyverse)

install.packages("anomalize")
library('anomalize')

install.packages('tibbletime')
library(tibbletime)

install.packages('timetk')
library(timetk)

```


```{r}
sales <- read.csv('http://bit.ly/CarreFourSalesDataset')
head(sales)

```


```{r}
# Checking the dimensions of the dataset
dim(sales)
```


```{r}
#Checking the structure of the dataset
str(sales)
```


```{r}
#Changing the date column to its appropriate data type.
sales$Date <- as.Date(sales$Date, "%m/%d/%Y")
str(sales)

```


```{r}
# find the number of missing values in each column using is.na() and colSums() functions
colSums(is.na(sales))

```
No missing values

```{r}
# totalling the sales based on their common shared dates
sales_tot <- aggregate(sales$Sales, by = list(Date = sales$Date), FUN = sum)

head(sales_tot)

```


```{r}
#Changing the column name x to total sales.
names(sales_tot)[2] <- 'Total_sales'
head(sales_tot)

```


```{r}
# Converting data frame to a tibble time (tbl_time)
# tbl_time have a time index that contains information about which column 
# should be used for time-based subsetting and other time-based manipulation,
sales= tbl_time(sales, Date)
class(sales)

```


```{r}
# time_decompose() - this function would help with time series decomposition.
# anomalize() - 
# We perform anomaly detection on the decomposed data using 
# the remainder column through the use of the anomalize() function
# We create the lower and upper bounds around the “observed” values 
# through the use of the time_recompose() function, which recomposes 
# the lower and upper bounds of the anomalies around the observed values.
# we now plot using plot_anomaly_decomposition() to visualize out data. 
options(repr.plot.width = 20, repr.plot.height = 20)
tidyverse_cran_downloads %>%
    time_decompose(count) %>%
    anomalize(remainder) %>%
    time_recompose() %>%
    plot_anomalies(time_recomposed = TRUE, ncol = 3, alpha_dots = 0.5)

```

